# Site settings
title: Suzanne Wadsworth
email: smwadsworth@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Suzanne Wadsworth is a designer, maker, and purveyor of knitwear and other knitted Goods in Asheville, North Carolina.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.suzannewadsworth.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
